# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-08 23:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_auto_20160908_1536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compras',
            old_name='nome_cliente',
            new_name='nome',
        ),
    ]
